---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-secrets
type: Opaque
stringData:
  access-key: {{ .Values.s3.AccessKeyId | b64enc }}
  secret-key: {{ .Values.s3.SecretKeyId | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-usgs-secrets
type: Opaque
stringData:
  username: {{ .Values.usgs.username }}
  password: {{ .Values.usgs.password }}
