{{- range $.Values.workfinder.jobs }}
---

apiVersion: batch/v1
kind: CronJob
metadata:
    name: {{ $.Release.Name }}-{{ . }}
spec:
    schedule: {{ $.Values.workfinder.cronString | quote }}
    concurrencyPolicy: Forbid
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        -   name: {{ $.Release.Name }}-{{ . }}
                            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
                            imagePullPolicy: {{ $.Values.image.pullPolicy }}
                            command:
                                - python
                                - -m
                                - workfinder.workfinder
                                - --limit
                                - {{ $.Values.workfinder.batchSize | quote}}
                                - {{ . | upper | replace "-" "_" }}
                            env:
                                -   name: APP_REGION
                                    value: {{ $.Values.region | title }}
                                -   name: AWS_BUCKET
                                    value: {{ $.Values.s3.bucket | quote }}
                                -   name: AWS_ACCESS_KEY_ID
                                    valueFrom:
                                        secretKeyRef:
                                            name: s3-secrets
                                            key: access-key
                                -   name: AWS_SECRET_ACCESS_KEY
                                    valueFrom:
                                        secretKeyRef:
                                            name: s3-secrets
                                            key: secret-key
                                -   name: USGS_USERNAME
                                    valueFrom:
                                        secretKeyRef:
                                            name: usgs-secrets
                                            key: username
                                -   name: USGS_PASSWORD
                                    valueFrom:
                                        secretKeyRef:
                                            name: usgs-secrets
                                            key: password
                                -   name: NATS_URL
                                    value: {{ $.Values.nats.url | quote }}
                                -   name: REDIS_HOST
                                    value: {{ $.Values.redis.host | quote }}
                                -   name: REDIS_PORT
                                    value: {{ $.Values.redis.port | quote }}
                    restartPolicy: Never

{{- end }}
