---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: workfinder-landsat8
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: workfinder-landsat8
            image: satapps/workfinder:0.1.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/python
            - -m
            - workfinder.workfinder
            - landsat8
            env:
                - name: APP_REGION
                  value: "fiji"
                - name: AWS_BUCKET
                  value: "public-eo-data"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                      secretKeyRef:
                          name: s3_secrets
                          key: access_key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                      secretKeyRef:
                          name: s3_secrets
                          key: secret_key
                - name: NATS_URL
                  value: "nats://something.something.com"
                - name: REDIS_HOST
                  value: "redis-master"
                - name: REDIS_PORT
                  value: "6379"
          restartPolicy: Never

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: workfinder-landsat8-wait
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: workfinder-landsat8-wait
            image: satapps/workfinder:0.1.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/python
            - -m
            - workfinder.wait_for_order
            - landsat8
            env:
                - name: APP_REGION
                  value: "fiji"
                - name: AWS_BUCKET
                  value: "public-eo-data"
                - name: AWS_ACCESS_KEY_ID
                  value: "jdhfgjkldfshgjkfdhs"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "jdhfgjkldfshgjkfdhs"
                - name: NATS_URL
                  value: "nats://something.something.com"
                - name: REDIS_HOST
                  value: "redis-master"
                - name: REDIS_PORT
                  value: "6379"
          restartPolicy: Never
