image:
  repository: "satapps/workfinder"
  tag: "0.2.38"
  pullPolicy: IfNotPresent

region: "fiji"

nats:
    host: "nats-ips"
    port: 4222

redis:
    host: "redis-master.ard.svc.cluster.local"
    port: 6379

app:
    region: "fiji"
    crs: "EPSG:32760"
    tempDir: "/tmp"

workfinder:
    batchSize: 100
    cronString: "*/5 * * * *"
    jobs:
        - landsat4-ard
        - landsat5-ard
        - landsat5-wofs
        - landsat5-wofs-ard
        - landsat5-mlwater
        - landsat5-mlwater-ard
        - landsat7-ard
        - landsat7-wofs
        - landsat7-wofs-ard
        - landsat7-mlwater
        - landsat7-mlwater-ard
        - landsat8-ard
        - landsat8-wofs
        - landsat8-wofs-ard
        - landsat8-mlwater
        - landsat8-mlwater-ard
        - s2-ard
        - s2-wofs
        - s2-

wait:
    cronString: "*/5 * * * *"
    jobs:
        - landsat8

s3:
    AccessKeyId: "something"
    SecretKeyId: "something"
    bucket: "public-eo-data"
    endpoint: "https://s3.amazonaws.com"
    imageryPath: "imagery"
    stacPath: "stac"

usgs:
    username: "something"
    password: "something"

copernicus:
    username: "something"
    password: "something"

s1:
    redisProcessedChannel: "s1-processed"
    ardStacCollectionPath: "s1-ard/stac"
    ardStacCollectionPathMlwater: "s1-ard-mlwater/stac"

s2:
    redisProcessedChannel: "s2-processed"
    ardStacCollectionPath: "s2-ard/stac"
    ardStacCollectionPathMlwater: "s2-ard-mlwater/stac"
    ardStacCollectionPathWofs: "s2-ard-wofs/stac"

landsat8:
    redisProcessedChannel: "landsat8-processed"
    redisPendingChannel: "landsat8-pending"
    ardStacCollectionPath8: "landsat8-ard/stac"
    ardStacCollectionPath8Mlwater: "landsat8-ard-mlwater/stac"
    ardStacCollectionPath8Wofs: "landsat8-ard-wofs/stac"

landsat7:
    ardStacCollectionPath7: "landsat7-ard/stac"
    ardStacCollectionPath7Mlwater: "landsat7-ard-mlwater/stac"
    ardStacCollectionPath7Wofs: "landsat7-ard-wofs/stac"

landsat5:
    ardStacCollectionPath5: "landsat5-ard/stac"
    ardStacCollectionPath5Mlwater: "landsat5-ard-mlwater/stac"
    ardStacCollectionPath5Wofs: "landsat5-ard-wofs/stac"

mlWater:
    redisProcessedChannel: "mlwater-processed"
    wofsSummaryPath: "wofs-summary"
