image:
  repository: "satapps/workfinder"
  tag: "0.2.34"
  pullPolicy: IfNotPresent

region: "fiji"

nats:
    url: "nats://nats.nats.svc.cluster.local:4222"

redis:
    host: "redis-master.ard.svc.cluster.local"
    port: 6379

workfinder:
    batchSize: 100
    cronString: "*/5 * * * *"
    jobs:
        - landsat4-ard
        - landsat5-ard
        - landsat5-wofs
        - landsat5-wofs-ard
        - landsat5-mlwater
        - landsat5-mlwater-ard
        - landsat7-ard
        - landsat7-wofs
        - landsat7-wofs-ard
        - landsat7-mlwater
        - landsat7-mlwater-ard
        - landsat8-ard
        - landsat8-wofs
        - landsat8-wofs-ard
        - landsat8-mlwater
        - landsat8-mlwater-ard
        - s2-ard
        - s2-wofs
        - s2-

wait:
    cronString: "*/5 * * * *"
    jobs:
        - landsat8

s3:
    AccessKeyId: "something"
    SecretKeyId: "something"
    bucket: "public-eo-data"

usgs:
    username: "something"
    password: "something"


