image:
  repository: "satapps/workfinder"
  tag: "0.2.38"
  pullPolicy: IfNotPresent

region: "fiji"

nats:
    host: "nats-ips"
    port: 4222

redis:
    host: "redis-master.ard.svc.cluster.local"
    port: 6379

app:
    region: "fiji"
    crs: "EPSG:32760"
    tempDir: "/tmp"

workfinder:
    batchSize: 500
    cronString: "0 0 * * SAT"
    jobs:
        #- landsat4-ard
        #- landsat5-ard
        #- landsat5-wofs
        #- landsat5-wofs-ard
        #- landsat5-mlwater
        #- landsat5-mlwater-ard
        #- landsat7-ard
        #- landsat7-wofs
        #- landsat7-wofs-ard
        #- landsat7-mlwater
        #- landsat7-mlwater-ard
        - landsat8-ard
        - landsat8
        #- landsat8-wofs
        #- landsat8-wofs-ard
        #- landsat8-mlwater
        #- landsat8-mlwater-ard
        #- s2-ard
        #- s2-wofs
        #- s2-

wait:
    cronString: "*/5 * * * *"
    jobs:
        - landsat8

s3:
    accessKeyId: ""
    secretKeyId: ""
    region: "eu-west-2"
    bucket: "public-eo-data"
    endpoint: "https://s3-uk-1.sa-catapult.co.uk"
    imageryPath: "common_sensing2"
    stacPath: "stac_catalogs2/cs_stac"

usgs:
    username: ""
    password: ""
    apiendpoint: "https://espa.cr.usgs.gov/api/v1/"

copernicus:
    username: "something"
    password: "something"

s1:
    redisProcessedChannel: "s1-processed"
    ardStacCollectionPath: "s1-ard/stac"
    ardStacCollectionPathMlwater: "s1-ard-mlwater/stac"

s2:
    redisProcessedChannel: "s2-processed"
    ardStacCollectionPath: "s2-ard/stac"
    ardStacCollectionPathMlwater: "s2-ard-mlwater/stac"
    ardStacCollectionPathWofs: "s2-ard-wofs/stac"

landsat8:
    redisProcessedChannel: "jobLS"
    redisPendingChannel: "landsat8_ordered"
    ardStacCollectionPath8: "landsat_8/collection.json"
    ardStacCollectionPath8Mlwater: ""
    ardStacCollectionPath8Wofs: ""

landsat7:
    ardStacCollectionPath7: ""
    ardStacCollectionPath7Mlwater: ""
    ardStacCollectionPath7Wofs: ""

landsat5:
    ardStacCollectionPath5: ""
    ardStacCollectionPath5Mlwater: ""
    ardStacCollectionPath5Wofs: ""

mlWater:
    redisProcessedChannel: ""
    wofsSummaryPath: ""
