name: publish docker containers

on:
  release:
    types: [created]

jobs:
  workfinder:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set version
        id: version
        run: echo "::set-output name=version_string::$(python setup.py --version)"

      - name: Build and push Server
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: satapps/workfinder:${{ steps.version.outputs.version_string }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
